<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
   <xacro:include filename="$(find unitree_robot)/urdf/common_inertia.xacro" />
    <xacro:macro name="cylinder_base_xacro" params="name length radius parent_link xyz">
        <!-- 圆柱体本体 -->
        <link name="${name}_cylinder_link">
            <visual>
                <origin xyz="0 0 ${length/2.0}" rpy="0 0 0" />
                <geometry>
                    <cylinder length="${length}" radius="${radius}" />
                </geometry>
                <material name="green">
                    <color rgba="0.1 0.8 0.1 0.6"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0 0 ${length/2.0}" rpy="0 0 0" />
                <geometry>
                    <cylinder length="${length}" radius="${radius}" />
                </geometry>
            </collision>
            <!-- 质量设为极小值，使其不影响小车运动 -->
            <xacro:cylinder_inertia m="0.001" r="${radius}" h="${length}"/>
        </link>

        <!-- 连接到父链接的关节 -->
        <joint name="${name}_cylinder_joint" type="fixed">
            <parent link="${parent_link}" />
            <child link="${name}_cylinder_link" />
            <origin xyz="${xyz}" rpy="0 0 0" />
        </joint>

    </xacro:macro>

</robot>

